version: '3.8'

services:
  backend:
    build: 
      context: ./CarShopBackend
      dockerfile: Dockerfile
    container_name: carshop-backend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DATABASE_URL=postgres://postgres:carshopdatabase@db.rjlewidauwbneruxdspn.supabase.co:5432/postgres
      - NODE_ENV=production
      - NODE_OPTIONS=--dns-result-order=ipv4first
      - DEBUG=*
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (r) => process.exit(r.statusCode === 200 ? 0 : 1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - ./CarShopBackend/uploads:/usr/src/app/uploads
    networks:
      - carshop-network
    restart: unless-stopped

  frontend:
    build:
      context: ./CarShopFrontend
      dockerfile: Dockerfile
    container_name: carshop-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - carshop-network

networks:
  carshop-network:
    driver: bridge

volumes:
  uploads:
