services:
  - type: web
    name: carshop-backend
    env: node
    buildCommand: npm install
    startCommand: node index.js    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false
      - key: NODE_OPTIONS
        value: --dns-result-order=ipv4first
      - key: UV_THREADPOOL_SIZE
        value: "16"
      - key: PGHOST
        value: db.rjlewidauwbneruxdspn.supabase.co
      - key: PGSSLMODE
        value: require
      - key: SEQUELIZE_DISABLE_IPV6
        value: "true"
    healthCheckPath: /health
    disk:
      name: uploads
      mountPath: /usr/src/app/uploads
      sizeGB: 1
