services:
  - type: web
    name: carshop-backend
    env: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false
      - key: NODE_OPTIONS
        value: --dns-result-order=ipv4first
    healthCheckPath: /health
    disk:
      name: uploads
      mountPath: /usr/src/app/uploads
      sizeGB: 1
